[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
allow_paths = [".", "./node_modules"]

remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/",
  "@chainlink/contracts/=node_modules/@chainlink/contracts/"
]
